export const sampleData = [
    {
        "id_number": "1",
        "link": "https://onlinelibrary-wiley-com.elib.tcd.ie/doi/pdfdirect/10.1002/rra.3507",
        "doi": " https://doi.org/10.1002/rra.3507",
        "title": "Communicating (nature-based) flood-mitigation schemes using flood-excess volume",
        "year": "2019",
        "country": "UK",
        "place_name": "Mytholmroyd",
        "latitude": "53.7305",
        "longitude": "-1.9817",
        "indicator": "Water",
        "sub_indicator": "Flooding",
        "study_type": "Measurement",
        "study_duration": "Days",
        "nbs_type": "Water Structure",
        "nbs_setting": "Rural",
        "nbs_scale": "Single",
        "nbs_effect": "slow down the flow by increasing flood depths, in places where this is deemed acceptable, thus reducing flood peaks further downstream at critical locations"
    },
    {
        "id_number": "1",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "France",
        "place_name": "Biot",
        "latitude": "43.6294",
        "longitude": "7.0961",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "2",
        "link": "https://www.actahort.org/books/1215/1215_2.htm",
        "doi": "https://doi.org/10.17660/ActaHortic.2018.1215.2",
        "title": "Urban green technologies for energy saving: numerical simulation of heat transfer between green façades and green roofs and the local outdoor environment",
        "year": "2017",
        "country": "Italy",
        "place_name": "Bologna",
        "latitude": "44.5075",
        "longitude": "11.3514",
        "indicator": "Heat",
        "sub_indicator": "Thermal Comfort",
        "study_type": "Modelling",
        "study_duration": "N/A",
        "nbs_type": "Green Façade",
        "nbs_setting": "Urban",
        "nbs_scale": "Single",
        "nbs_effect": "thermal insulation, heat island effect reduction and in general energy saving at building and district scale"
    },
    {
        "id_number": "2",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "Green Roof",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "3",
        "link": "https://link-springer-com.elib.tcd.ie/content/pdf/10.1007/s11368-020-02731-y.pdf",
        "doi": "https://doi.org/10.1007/s11368-020-02731-y",
        "title": "Simplified performance assessment methodology for addressing soil quality of nature-based solutions",
        "year": "2020",
        "country": "France",
        "place_name": "Nantes",
        "latitude": "47.2181",
        "longitude": "-1.5528",
        "indicator": "Water",
        "sub_indicator": "Flooding",
        "study_type": "Measurement",
        "study_duration": "Years",
        "nbs_type": "Green Space",
        "nbs_setting": "Urban",
        "nbs_scale": "Many",
        "nbs_effect": "Regulation of local climate and storm water regulation; contribution to urban biodiversity; increase organic carbon concentration; restore soil fertility"
    },
    {
        "id_number": "3",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "France",
        "place_name": "Nancy",
        "latitude": "48.6908",
        "longitude": "6.1825",
        "indicator": "Other",
        "sub_indicator": "Ecology",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "Green Roof",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "3",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "Czech Republic",
        "place_name": "Buštěhrad",
        "latitude": "50.1553",
        "longitude": "14.1886",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "4",
        "link": "Assessing allergenicity in urban parks: A nature-based solution to reduce the impact on public health - ScienceDirect (tcd.ie)",
        "doi": "https://doi.org/10.1016/j.envres.2017.02.015",
        "title": "Assessing allergenicity in urban parks: A nature-based solution to reduce the impact on public health",
        "year": "2017",
        "country": "Spain",
        "place_name": "Madrid",
        "latitude": "40.4167",
        "longitude": "-3.7003",
        "indicator": "Other",
        "sub_indicator": "Other",
        "study_type": "Measurement",
        "study_duration": "N/A",
        "nbs_type": "Green Space",
        "nbs_setting": "Urban",
        "nbs_scale": "Single",
        "nbs_effect": "1.The lack of correlation with other conventional variables used in landscape designs.\r\n2. It can be used as a tool in environmental analysis.\r\n3.Complies with principle of scalability"
    },
    {
        "id_number": "5",
        "link": "Cork as a sustainable carbon source for nature-based solutions treating hydroponic wastewaters – Preliminary batch studies - ScienceDirect (tcd.ie)",
        "doi": "https://doi.org/10.1016/j.scitotenv.2018.08.365",
        "title": "Cork as a sustainable carbon source for nature-based solutions treating hydroponic wastewaters - Preliminary batch studies",
        "year": "2019",
        "country": "Denmark",
        "place_name": "Aarhus",
        "latitude": "56.1572",
        "longitude": "10.2107",
        "indicator": "Water",
        "sub_indicator": "Water Quality",
        "study_type": "Experiment",
        "study_duration": "Days",
        "nbs_type": "Other",
        "nbs_setting": "Urban",
        "nbs_scale": "Single",
        "nbs_effect": "1. Variance on the content of suberin across species.\r\n2.The PZC of cork was between pH 5 and 6."
    },
    {
        "id_number": "6",
        "link": " Nature-Based Solution along High-Energy Eroding Sandy Coasts: Preliminary Tests on the Reinstatement of Natural Dynamics in Reprofiled Coastal Dunes (researchgate.net)",
        "doi": "https://doi.org/10.3390/w11122518",
        "title": "Nature-Based Solution along High-Energy Eroding Sandy Coasts: Preliminary Tests on the Reinstatement of Natural Dynamics in Reprofiled Coastal Dunes",
        "year": "2019",
        "country": "France",
        "place_name": "Bordeaux",
        "latitude": "44.8350",
        "longitude": "-0.5755",
        "indicator": "Other",
        "sub_indicator": "Erosion",
        "study_type": "Experiment",
        "study_duration": "Years",
        "nbs_type": "Vegetation",
        "nbs_setting": "Urban",
        "nbs_scale": "Single",
        "nbs_effect": "1. The interannual variability in vegetation dynamics could affect blowout growth.\r\n2. The area of bare sand landward of the elongated of notches increased and the notch floor remained nonvegetated implying a loss of vegetation cover."
    },
    {
        "id_number": "7",
        "link": "The reduction of Chlorella vulgaris concentrations through UV-C radiation treatments: A nature-based solution (NBS) - ScienceDirect (tcd.ie)",
        "doi": "https://doi.org/10.1016/j.envres.2017.03.007",
        "title": "The reduction of Chlorella vulgaris concentrations through UV-C radiation treatments: A nature-based solution (NBS)",
        "year": "2017",
        "country": "USA",
        "place_name": "Grand Rapids",
        "latitude": "42.9655",
        "longitude": "-85.6702",
        "indicator": "Other",
        "sub_indicator": "Other",
        "study_type": "Measurement",
        "study_duration": "Hours",
        "nbs_type": "Other",
        "nbs_setting": "Urban",
        "nbs_scale": "Single",
        "nbs_effect": "1. The 30W UV-C radiation had a stronger effect than the 15W UV-C radiation on reducing algal concentration.\r\n2.UV-C had the greatest impact on SP2 samples"
    },
    {
        "id_number": "8",
        "link": "Do green spaces affect the spatiotemporal changes of PM 2.5 in Nanjing? | Ecological Processes | Full Text (springeropen.com)",
        "doi": "https://doi.org/10.1186/s13717-016-0052-6",
        "title": "Do green spaces affect the spatiotemporal changes of PM2.5 in Nanjing?",
        "year": "2016",
        "country": "China",
        "place_name": "Nanjing",
        "latitude": "32.0500",
        "longitude": "118.7667",
        "indicator": "Air",
        "sub_indicator": "Particulate Matter",
        "study_type": "Measurement",
        "study_duration": "Years",
        "nbs_type": "Green Space",
        "nbs_setting": "Urban",
        "nbs_scale": "Many",
        "nbs_effect": "Reduce Respiratory Diseases, Improve Ambient Air Quality"
    },
    {
        "id_number": "9",
        "link": "https://www-sciencedirect-com.elib.tcd.ie/science/article/pii/S0360132320305515?via%3Dihub",
        "doi": "https://doi.org/10.1016/j.buildenv.2020.107179",
        "title": "Analysis of potential benefits on flood mitigation of a CAM green roof in Mediterranean urban areas ",
        "year": "2020",
        "country": "Italy",
        "place_name": "Cagliari",
        "latitude": "39.2500",
        "longitude": "9.0500",
        "indicator": "Water",
        "sub_indicator": "Flooding",
        "study_type": "Modelling",
        "study_duration": "Years",
        "nbs_type": "Green Roof",
        "nbs_setting": "Urban",
        "nbs_scale": "Single",
        "nbs_effect": "Reducing runoff, increase biodiversity, energy savings, reduce pollution, aesthetically pleasant"
    },
    {
        "id_number": "10",
        "link": "https://www.sciencedirect.com/science/article/abs/pii/S0044848619326195",
        "doi": "https://doi.org/10.1016/j.aquaculture.2020.735502",
        "title": "Seagrass meadows improve inflowing water quality in aquaculture ponds ",
        "year": "2020",
        "country": "Portugal",
        "place_name": "Tavira",
        "latitude": "37.1258",
        "longitude": "-7.6498",
        "indicator": "Water",
        "sub_indicator": "Water Quality",
        "study_type": "Measurement",
        "study_duration": "Months",
        "nbs_type": "Vegetation",
        "nbs_setting": "Coastal",
        "nbs_scale": "Single",
        "nbs_effect": "Increase water quality, increase biodiversity"
    },
    {
        "id_number": "11",
        "link": "https://doi.org/10.1002/ldr.3113",
        "doi": "https://doi.org/10.1002/ldr.3113",
        "title": "Multi-functionality of nature-based and other urban sustainability solutions: New York City study",
        "year": "2018",
        "country": "USA",
        "place_name": "Manhattan",
        "latitude": "40.7903",
        "longitude": "-73.9597",
        "indicator": "Water",
        "sub_indicator": "Other",
        "study_type": "Measurement",
        "study_duration": "Years",
        "nbs_type": "Green Roof",
        "nbs_setting": "Urban",
        "nbs_scale": "Many",
        "nbs_effect": "Rooftop Solar PV  shows highst reduction Energy Use, and Carbon Dioxide Emissions only.                                                                                                                                                                                      Green Roofs have equal reductions on Water Management, Energy Use, and Carbon Dioxide Emissions.                                                                                                                                                       Retrofitted Windows have higher reduction Energy Use, and Carbon Dioxide Emissions only.                                                                                                                                                                                                                                                                                Permeable Pavements have higher reduction on Water Management only."
    },
    {
        "id_number": "11",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "Air",
        "sub_indicator": "Carbon Oxides",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "Permeable Pavement",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "12",
        "link": "https://doi.org/10.1016/j.scitotenv.2020.138061",
        "doi": "https://doi.org/10.1016/j.scitotenv.2020.138061",
        "title": "Can nature-based solutions contribute to water security in Bhopal?",
        "year": "2020",
        "country": "India",
        "place_name": "Bhopal",
        "latitude": "23.1395",
        "longitude": "77.4086",
        "indicator": "Water",
        "sub_indicator": "Other",
        "study_type": "Measurement",
        "study_duration": "Months",
        "nbs_type": "Water Structure",
        "nbs_setting": "Rural",
        "nbs_scale": "Many",
        "nbs_effect": "4.26% fell into a ‘very high’ groundwater potential class.                                                                                                                                                                                                                                                  29.29% fell into a ‘high’ groundwater potential  class.\r\n45.79%fell into a ‘moderate’ groundwater potential class.                                                                                                                                                                                                                                          \r\n20.64%,fell into a ‘low’ groundwater potential class."
    },
    {
        "id_number": "13",
        "link": "https://doi.org/10.1016/j.geoforum.2020.07.011",
        "doi": "https://doi.org/10.1016/j.geoforum.2020.07.011",
        "title": "Scaling-up nature-based solutions. Lessons from the Living Melbourne strategy",
        "year": "2020",
        "country": "Australia",
        "place_name": "Melbourne",
        "latitude": "-37.8136",
        "longitude": "144.9631",
        "indicator": "Air",
        "sub_indicator": "Other",
        "study_type": "Measurement",
        "study_duration": "Months",
        "nbs_type": "Green Façade",
        "nbs_setting": "Urban",
        "nbs_scale": "Many",
        "nbs_effect": "Encouraging incrased in return of Biodiversity lost (+5.53 % compared to previous year).                                                                                                                                                                                  Significant reduction in Air pollution, Heat Waves, Flooding, Droughts(-31.85 % compared to previous year) .                                                                                                                                              \r\nSignifacant incrased in Residents' health and wellbeing (-25.15 % compared to previous year)"
    },
    {
        "id_number": "13",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "Water",
        "sub_indicator": "Flooding",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "Green Space",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "13",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "Heat",
        "sub_indicator": "Thermal Comfort",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "13",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "Other",
        "sub_indicator": "Ecology",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "14",
        "link": "https://libraetd.lib.virginia.edu/public_view/pz50gw51d",
        "doi": "https://doi.org/10.18130/V3HT2GB5P",
        "title": "Evaluating Nature-Based Solutions to Storm Wave Impacts in the Virginia Coast Reserve",
        "year": "2018",
        "country": "USA",
        "place_name": "Richmond",
        "latitude": "37.5408",
        "longitude": "-77.4339",
        "indicator": "Water",
        "sub_indicator": "Erosion",
        "study_type": "Measurement",
        "study_duration": "Months",
        "nbs_type": "Water Structure",
        "nbs_setting": "Coastal",
        "nbs_scale": "Many",
        "nbs_effect": "Constructed oyster reefs were effective at dampening waves up to 46% when water levels were low to moderate (< mean water depth);                                                                                                          Marsh vegetation was found to dampen waves by an average of 78% over a 20-meter marsh transect when water depths were high enough to flood the marsh.                                                                                    These results suggest that combining constructed oyster reefs with marsh vegetation may offer effective and sustainable long-term reduction in marsh vulnerability."
    },
    {
        "id_number": "15",
        "link": "https://www.researchgate.net/publication/309220469_Linear_Parks_along_Urban_Rivers_Perceptions_of_Thermal_Comfort_and_Climate_Change_Adaptation_in_Cyprus",
        "doi": "http://dx.doi.org/10.3390/su8101023",
        "title": "Linear Parks along Urban Rivers: Perceptions of Thermal Comfort and Climate Change Adaptation in Cyprus",
        "year": "2016",
        "country": "Cyprus",
        "place_name": "Nicosia",
        "latitude": "35.1667",
        "longitude": "33.3667",
        "indicator": "Water",
        "sub_indicator": "Flooding",
        "study_type": "Measurement",
        "study_duration": "Months",
        "nbs_type": "Green Space",
        "nbs_setting": "Urban",
        "nbs_scale": "Single",
        "nbs_effect": "Relatively low cooling effect (0,5 Celcius) in early morning and afternoon hours, Flood protection not recognised"
    },
    {
        "id_number": "15",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "Heat",
        "sub_indicator": "Thermal Comfort",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "16",
        "link": "https://www.sciencedirect.com/science/article/pii/S0048969720316958",
        "doi": "https://doi.org/10.1016/j.scitotenv.2020.138182",
        "title": "Using green to cool the grey: Modelling the cooling effect of green spaces with a high spatial resolution",
        "year": "2020",
        "country": "Portugal",
        "place_name": "Almada",
        "latitude": "38.6757",
        "longitude": "-9.165",
        "indicator": "Heat",
        "sub_indicator": "Thermal Comfort",
        "study_type": "Modelling",
        "study_duration": "Months",
        "nbs_type": "Green Space",
        "nbs_setting": "Urban",
        "nbs_scale": "Single",
        "nbs_effect": " green spaces with reduced areas can regulate microclimate, alleviating temperature by 1–3 °C and increasing moisture by 2–8%, on average."
    },
    {
        "id_number": "17",
        "link": "https://www.researchgate.net/publication/342674454_Experimental_Assessment_of_the_Flow_Resistance_of_Coastal_Wooden_Fences",
        "doi": "http://dx.doi.org/10.3390/w12071910",
        "title": "Experimental Assessment of the Flow Resistance of Coastal Wooden Fences",
        "year": "2020",
        "country": "Vietnam",
        "place_name": "Can Tho",
        "latitude": "10.0936",
        "longitude": "106.2383",
        "indicator": "Water",
        "sub_indicator": "Erosion",
        "study_type": "Modelling",
        "study_duration": "N/A",
        "nbs_type": "Water Structure",
        "nbs_setting": "Coastal",
        "nbs_scale": "Single",
        "nbs_effect": "Bulk drag coefficient strongly dependent on the fence’s porosity; Greater specific surface area of fence increase laminar drag and thus increasing drag coefficient"
    },
    {
        "id_number": "18",
        "link": "https://www.sciencedirect.com/science/article/pii/S1618866717304119?via%3Dihub",
        "doi": "https://doi.org/10.1016/j.ufug.2018.01.018",
        "title": "Subjective perception of noise exposure in relation to urban green space availability",
        "year": "2018",
        "country": "Poland",
        "place_name": "Łódź",
        "latitude": "51.7591",
        "longitude": "19.4586",
        "indicator": "Noise",
        "sub_indicator": "Noise Reduction",
        "study_type": "Measurement",
        "study_duration": "N/A",
        "nbs_type": "Green Space",
        "nbs_setting": "Urban",
        "nbs_scale": "Many",
        "nbs_effect": "noise perception related to green space availability is small but statistically significant"
    },
    {
        "id_number": "19",
        "link": "https://www.sciencedirect.com/science/article/pii/S0048969719354804?via%3Dihub",
        "doi": "https://doi.org/10.1016/j.scitotenv.2019.135487",
        "title": "Creating urban green infrastructure where it is needed - A spatial ecosystem service-based decision analysis of green roofs in Barcelona",
        "year": "2020",
        "country": "Spain",
        "place_name": "Barcelona",
        "latitude": "41.3879",
        "longitude": "2.1699",
        "indicator": "Heat",
        "sub_indicator": "Thermal Comfort",
        "study_type": "Modelling",
        "study_duration": "N/A",
        "nbs_type": "Green Roof",
        "nbs_setting": "Urban",
        "nbs_scale": "Many",
        "nbs_effect": "Demand for ecosystem services that green roofs potentially might provide, particularly in dense residential neighborhoods"
    },
    {
        "id_number": "19",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "Water",
        "sub_indicator": "Flooding",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "19",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "Other",
        "sub_indicator": "Other",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "20",
        "link": "https://onlinelibrary-wiley-com.elib.tcd.ie/doi/full/10.1002/ldr.3102",
        "doi": "https://doi.org/10.1002/ldr.3102",
        "title": "Green roofs: Effects of plant species used on runoff",
        "year": "2018",
        "country": "China",
        "place_name": "Qibao",
        "latitude": "31.1578",
        "longitude": "121.3514",
        "indicator": "Water",
        "sub_indicator": "Flooding",
        "study_type": "Measurement",
        "study_duration": "Years",
        "nbs_type": "Green Roof",
        "nbs_setting": "Urban",
        "nbs_scale": "Single",
        "nbs_effect": "Water retention capacity（From best to worst）：A. stolonifera、L. perenne and P.、F. arundinacea、S. lineare and C. repens"
    },
    {
        "id_number": "21",
        "link": "https://www-sciencedirect-com.elib.tcd.ie/science/article/pii/S0013935117308939?via%3Dihub",
        "doi": "https://doi.org/10.1016/j.envres.2017.05.016",
        "title": "Hydro-dam - A nature-based solution or an ecological problem: The fate of the Tonle Sap Lake",
        "year": "2017",
        "country": "China",
        "place_name": "Siem Reap District",
        "latitude": "13.3333",
        "longitude": "103.8333",
        "indicator": "Water",
        "sub_indicator": "Other",
        "study_type": "Modelling",
        "study_duration": "Years",
        "nbs_type": "Water Structure",
        "nbs_setting": "Rural",
        "nbs_scale": "Single",
        "nbs_effect": "lake open water area decrease; Water flow decrease;"
    },
    {
        "id_number": "22",
        "link": "https://www.mdpi.com/2071-1050/11/22/6361",
        "doi": "https://doi.org/10.3390/su11226361",
        "title": "Planning Nature-Based Solutions for Urban Flood Reduction and Thermal Comfort Enhancement",
        "year": "2019",
        "country": "Thailand",
        "place_name": "Din Daeng District",
        "latitude": "13.7895",
        "longitude": "100.5666",
        "indicator": "Heat",
        "sub_indicator": "Thermal Comfort",
        "study_type": "Modelling",
        "study_duration": "Years",
        "nbs_type": "Green Roof",
        "nbs_setting": "Urban",
        "nbs_scale": "Many",
        "nbs_effect": "Effectiveness: Rain Garden> Green Roof> BioRetention> Permeable Pavement"
    },
    {
        "id_number": "22",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "Water",
        "sub_indicator": "Flooding",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "Permeable Pavement",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "22",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "Vegetation",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "22",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "Other",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "23",
        "link": "https://pdxscholar.library.pdx.edu/cgi/viewcontent.cgi?article=1247&context=usp_fac",
        "doi": "https://doi.org/10.3390/atmos10050282",
        "title": "Nature-Based Designs to Mitigate Urban Heat: The Efficacy of Green Infrastructure Treatments in Portland, Oregon",
        "year": "2019",
        "country": "USA",
        "place_name": "Portland",
        "latitude": "45.5200",
        "longitude": "-122.6819",
        "indicator": "Heat",
        "sub_indicator": "Thermal Comfort",
        "study_type": "Modelling",
        "study_duration": "Years",
        "nbs_type": "Green Roof",
        "nbs_setting": "Urban",
        "nbs_scale": "Many",
        "nbs_effect": "Effectiveness: Combination> More Trees> GreenRoof"
    },
    {
        "id_number": "23",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "Green Space",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "24",
        "link": "https://doi.org/10.1088/1748-9326/ab502c",
        "doi": "https://doi.org/10.1088/1748-9326/ab502c",
        "title": "A green infrastructure spatial planning model for evaluating ecosystem service tradeoffs and synergies across three coastal megacities",
        "year": "2019",
        "country": "USA",
        "place_name": "New York",
        "latitude": "40.7130",
        "longitude": "-74.0072",
        "indicator": "Water",
        "sub_indicator": "Flooding",
        "study_type": "Modelling",
        "study_duration": "Years",
        "nbs_type": "Green Space",
        "nbs_setting": "Urban",
        "nbs_scale": "Many",
        "nbs_effect": "1. Managing stormwater\r\n2. Reducing social vulnerability\r\n3. Increasing access to green space\r\n4 Reducing urban heat island effect (UHI)\r\n5. Improving air quality\r\n6. Increasing landscape connectivity"
    },
    {
        "id_number": "24",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "Los Angeles",
        "latitude": "34.0522",
        "longitude": "-118.2433",
        "indicator": "",
        "sub_indicator": "Human Health",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "Vegetation",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "24",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "Phillippines",
        "place_name": "Manila",
        "latitude": "14.5823",
        "longitude": "120.9748",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "25",
        "link": "https://doi.org/10.1061/(ASCE)HY.1943-7900.0001659",
        "doi": "https://doi.org/10.1061/(ASCE)HY.1943-7900.0001659",
        "title": "Knowledge-Based Predictive Tools to Assess Effectiveness of Natural and Nature-Based Solutions for Coastal Restoration and Protection Planning",
        "year": "2018",
        "country": "USA",
        "place_name": "Baton Rouge",
        "latitude": "30.4495",
        "longitude": "-91.0934",
        "indicator": "Water",
        "sub_indicator": "Flooding",
        "study_type": "Modelling",
        "study_duration": "N/A",
        "nbs_type": "Water Structure",
        "nbs_setting": "Coastal",
        "nbs_scale": "Single",
        "nbs_effect": "1. Retains sediment and nourishes marsh \r\n2. Creates new land + nourish existing land with fine sediments\r\n3. Influence innundation and salinity "
    },
    {
        "id_number": "25",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "Erosion",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "25",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "Ecology",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "26",
        "link": "https://doi.org/10.1002/hyp.11140",
        "doi": "https://doi.org/10.1002/hyp.11140",
        "title": "A modelling framework for evaluation of the hydrological impacts of nature‐based approaches to flood risk management, with application to in‐channel interventions across a 29‐km2 scale catchment in the United Kingdom",
        "year": "2017",
        "country": "UK",
        "place_name": "Thirsk",
        "latitude": "54.2325",
        "longitude": "-1.3428",
        "indicator": "Water",
        "sub_indicator": "Flooding",
        "study_type": "Modelling",
        "study_duration": "Days",
        "nbs_type": "Water Structure",
        "nbs_setting": "Rural",
        "nbs_scale": "Single",
        "nbs_effect": "In-channel barriers insfficient to reduce peak discharge  in stormwater runoffs"
    },
    {
        "id_number": "27",
        "link": "http://dx.doi.org/10.1098/rsta.2019.0320",
        "doi": "http://dx.doi.org/10.1098/rsta.2019.0320",
        "title": "Potential and limitation of air pollution mitigation by vegetation and uncertainties of deposition-based evaluations",
        "year": "2020",
        "country": "UK",
        "place_name": "Sheffield",
        "latitude": "53.3836",
        "longitude": "-1.4669",
        "indicator": "Air",
        "sub_indicator": "Ozone",
        "study_type": "Modelling",
        "study_duration": "Years",
        "nbs_type": "Vegetation",
        "nbs_setting": "Urban",
        "nbs_scale": "Many",
        "nbs_effect": "lowering pollution (30% (22%) for SO2, 24% (19%) for NH3 and 15% (13%)\r\nfor O3),urban concentration by 1%,Emission reduction"
    },
    {
        "id_number": "27",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "Other",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "28",
        "link": "https://www.researchgate.net/publication/334158113_Groundwater_and_River_Flooding_The_Importance_of_Wetlands_in_Coastal_Zones",
        "doi": "http://dx.doi.org/10.2112/SI92-006.1",
        "title": "Groundwater and River Flooding: The Importance of Wetlands in Coastal Zones",
        "year": "2019",
        "country": "Mexico",
        "place_name": "Córdoba",
        "latitude": "18.8942",
        "longitude": "-96.9347",
        "indicator": "Water",
        "sub_indicator": "Flooding",
        "study_type": "Measurement",
        "study_duration": "Years",
        "nbs_type": "Wetlands",
        "nbs_setting": "Coastal",
        "nbs_scale": "Many",
        "nbs_effect": "divert water during extreme events,reduce flood impact,proper city planning"
    },
    {
        "id_number": "29",
        "link": "https://doi.org/10.1016/j.envint.2019.104945",
        "doi": "https://doi.org/10.1016/j.envint.2019.104946",
        "title": "Phytoremediation: Climate change resilience and sustainability assessment at a coastal brownfield redevelopment",
        "year": "2019",
        "country": "USA",
        "place_name": "Mill Valley",
        "latitude": "37.9067",
        "longitude": "-122.5475",
        "indicator": "Water",
        "sub_indicator": "Ecology",
        "study_type": "Modelling",
        "study_duration": "Years",
        "nbs_type": "Vegetation",
        "nbs_setting": "Coastal",
        "nbs_scale": "Many",
        "nbs_effect": "slower plume migration and life cycle primary impact"
    },
    {
        "id_number": "30",
        "link": "https://doi.org/10.1016/j.ibiod.2020.105084",
        "doi": "https://doi.org/10.1016/j.ibiod.2020.105085",
        "title": "Functional attributes and response of bacterial communities to nature-based fertilization during hydrocarbon remediation",
        "year": "2020",
        "country": "Nigeria",
        "place_name": "Port Harcourt",
        "latitude": "4.7715",
        "longitude": "7.0143",
        "indicator": "Other",
        "sub_indicator": "Ecology",
        "study_type": "Measurement",
        "study_duration": "Months",
        "nbs_type": "Other",
        "nbs_setting": "Rural",
        "nbs_scale": "Single",
        "nbs_effect": "improved bacterial diversity and richness,nutrient balance,favourable pH .TPH reduction(70.44%),TPH reduction(61%)"
    },
    {
        "id_number": "31",
        "link": "https://doi.org/10.1016/j.ecoleng.2018.05.017",
        "doi": "https://doi.org/10.1016/j.ecoleng.2018.05.018",
        "title": "Living shorelines enhance nitrogen removal capacity over time",
        "year": "2018",
        "country": "USA",
        "place_name": "Morehead City",
        "latitude": "34.7278",
        "longitude": "-76.7467",
        "indicator": "Other",
        "sub_indicator": "Water Quality",
        "study_type": "Measurement",
        "study_duration": "Months",
        "nbs_type": "Wetlands",
        "nbs_setting": "Coastal",
        "nbs_scale": "Many",
        "nbs_effect": "protect shorelines ,Denitrification efficiency >50%,negligible  N2O fluxes ,"
    },
    {
        "id_number": "32",
        "link": "https://link.springer.com/chapter/10.1007/978-3-319-77682-8_5",
        "doi": "https://doi.org/10.1007/978-3-319-77682-8_5",
        "title": "Increasing Hydrological Resilience Employing Nature-Based Solutions: A Modelling Approach to Support Spatial Planning",
        "year": "2018",
        "country": "Italy",
        "place_name": "Bari",
        "latitude": "41.1259",
        "longitude": "16.8721",
        "indicator": "Water",
        "sub_indicator": "Water Quality",
        "study_type": "Modelling",
        "study_duration": "N/A",
        "nbs_type": "Green Roof",
        "nbs_setting": "Urban",
        "nbs_scale": "Many",
        "nbs_effect": "Initially, the combined sewer system was not capable of managing all the volume during heavy precipitation events.\r\nThe NBS helped drainage network adequately manage storm water runoff efficiently."
    },
    {
        "id_number": "32",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "Flooding",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "Permeable Pavement",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "32",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "Water Structure",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "33",
        "link": "https://www.sciencedirect.com/science/article/pii/S1352231019307629",
        "doi": "https://doi.org/10.1016/j.atmosenv.2019.117123",
        "title": "Re-Naturing Cities: Evaluating the effects on future air quality in the city of Porto",
        "year": "2020",
        "country": "Portugal",
        "place_name": "Porto",
        "latitude": "41.1502",
        "longitude": "-8.6103",
        "indicator": "Air",
        "sub_indicator": "Particulate Matter",
        "study_type": "Measurement",
        "study_duration": "Years",
        "nbs_type": "Green Space",
        "nbs_setting": "Urban",
        "nbs_scale": "Many",
        "nbs_effect": "Temperature: -0.5 to -1 C\r\nGreen roofs and increased albedo: PM10 +0.6 to +1.5% ; NO2 +0.8% to 3.5% ; O3:  both increment and decrement variation with time od the day (no change in O3 for green roofs setting)\r\nGreen Urban Areas: PM10: -1% ; NO2 -3% ; O3 increased "
    },
    {
        "id_number": "33",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "Nitrogen Oxides",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "Green Roof",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "33",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "Ozone",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "34",
        "link": "https://www.sciencedirect.com/science/article/pii/S1352231018304977",
        "doi": "https://doi.org/10.1016/j.atmosenv.2018.07.044",
        "title": "Impacts of green infrastructures on aerodynamic flow and air quality in Porto's urban area",
        "year": "2018",
        "country": "Portugal",
        "place_name": "Porto",
        "latitude": "41.1502",
        "longitude": "-8.6103",
        "indicator": "Air",
        "sub_indicator": "Particulate Matter",
        "study_type": "Modelling",
        "study_duration": "Years",
        "nbs_type": "Green Space",
        "nbs_setting": "Urban",
        "nbs_scale": "Many",
        "nbs_effect": " NOx -19% ; PM10 -16%\r\nIncrease of pollutants in certain hotspot areas (as high as +60%) "
    },
    {
        "id_number": "34",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "Nitrogen Oxides",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "Green Roof",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "35",
        "link": "https://www.mdpi.com/2220-9964/9/7/461",
        "doi": "https://doi.org/10.3390/ijgi9070461",
        "title": "Spatiotemporal Variation of Urban Heat Islands for Implementing Nature-Based Solutions: A Case Study of Kurunegala, Sri Lanka",
        "year": "2020",
        "country": "Sri Lanka",
        "place_name": "Kurunegala",
        "latitude": "7.4833",
        "longitude": "80.3667",
        "indicator": "Heat",
        "sub_indicator": "Thermal Comfort",
        "study_type": "Measurement",
        "study_duration": "Years",
        "nbs_type": "Green Space",
        "nbs_setting": "Urban",
        "nbs_scale": "Many",
        "nbs_effect": "Reduction in Temperature\r\nLower temperature in areas with less grey infrastructure (peri-urban areas) as compared to areas with more grey infrastructure (city)"
    },
    {
        "id_number": "35",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "Green Roof",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "35",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "Green Façade",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "35",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "Other",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "36",
        "link": "https://www.sciencedirect.com/science/article/abs/pii/S0925857420300999",
        "doi": "https://doi.org/10.1016/j.ecoleng.2020.105811",
        "title": "Evaluation of the factors influencing the treatment performance of a livestock constructed wetland",
        "year": "2020",
        "country": "South Korea",
        "place_name": "Nonsan",
        "latitude": "36.2000",
        "longitude": "127.0833",
        "indicator": "Water",
        "sub_indicator": "Water Quality",
        "study_type": "Experiment",
        "study_duration": "Months",
        "nbs_type": "Wetlands",
        "nbs_setting": "Rural",
        "nbs_scale": "Single",
        "nbs_effect": "Reduction of turbidity (52% to 81%), TSS (61 to 82%), organics (34% to 50%), nutrients (10% to 48%), BOD (80%), COD(86%). However, further treatment is required."
    },
    {
        "id_number": "37",
        "link": "https://www.semanticscholar.org/paper/Water-Purifying-Capacity-of-Natural-Riverine-in-to-Sileshi-Awoke/3d96708bba4f190eb5bdc407873dc1c29d7621a4",
        "doi": "https://doi.org/10.3389/fenvs.2020.00039",
        "title": "Water Purifying Capacity of Natural Riverine Wetlands in Relation to Their Ecological Quality",
        "year": "2020",
        "country": "Ethiopia",
        "place_name": "Jimma",
        "latitude": "7.6785",
        "longitude": "36.8384",
        "indicator": "Water",
        "sub_indicator": "Water Quality",
        "study_type": "Measurement",
        "study_duration": "Years",
        "nbs_type": "Wetlands",
        "nbs_setting": "Freshwater",
        "nbs_scale": "Many",
        "nbs_effect": "Total Nitrogen: -18%; BOD: -88%; DO: +35%      Taxarichness (macro): +52.6%; Ethbios index: +100%; Shannon Diversity (macro): +40%; Shannon Diversity (diatom): +8%; Taxarichness (diatom): +50%; Percent of tolerant species: -13%"
    },
    {
        "id_number": "38",
        "link": "https://www.mdpi.com/2071-1050/12/15/5967",
        "doi": "https://doi.org/10.3390/su12155967",
        "title": "Spatial Compatibility of Implementing Nature-Based Solutions for Reducing Urban Heat Islands and Stormwater Pollution",
        "year": "2020",
        "country": "Germany",
        "place_name": "Mitte",
        "latitude": "52.5167",
        "longitude": "13.3667",
        "indicator": "Water",
        "sub_indicator": "Water Quality",
        "study_type": "Modelling",
        "study_duration": "Years",
        "nbs_type": "Vegetation",
        "nbs_setting": "Urban",
        "nbs_scale": "Many",
        "nbs_effect": "2270/14000 buildings or streets showed spatial matching of Urban heat island index and Stormwater pollution"
    },
    {
        "id_number": "38",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "Heat",
        "sub_indicator": "Thermal Comfort",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "Wetlands",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "39",
        "link": "https://iopscience-iop-org.elib.tcd.ie/article/10.1088/1748-9326/ab1827",
        "doi": "https://doi.org/10.1088/1748-9326/ab1827",
        "title": "Optimizing wetland restoration to improve water quality at a regional scale",
        "year": "2019",
        "country": "USA",
        "place_name": "Burlington",
        "latitude": "44.4758",
        "longitude": "-73.2119",
        "indicator": "Water",
        "sub_indicator": "Water Quality",
        "study_type": "Modelling",
        "study_duration": "Years",
        "nbs_type": "Wetlands",
        "nbs_setting": "Rural",
        "nbs_scale": "Many",
        "nbs_effect": "Twice the phosphorus reduction in wetlands, agricultural lands"
    },
    {
        "id_number": "40",
        "link": "https://www.mdpi.com/2071-1050/12/3/1240",
        "doi": "https://doi.org/10.3390/su12031240",
        "title": "Implementation of Nature-Based Solutions for Hydro-Meteorological Risk Reduction in Small Mediterranean Catchments: The Case of Portofino Natural Regional Park, Italy",
        "year": "2019",
        "country": "Italy",
        "place_name": "Genoa",
        "latitude": "44.4111",
        "longitude": "8.9328",
        "indicator": "Water",
        "sub_indicator": "Flooding",
        "study_type": "Modelling",
        "study_duration": "N/A",
        "nbs_type": "Other",
        "nbs_setting": "Coastal",
        "nbs_scale": "Many",
        "nbs_effect": "Mitigation of hydro-meteorological risk"
    },
    {
        "id_number": "40",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "Erosion",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "41",
        "link": "Comprehending the multiple ‘values’ of green infrastructure – Valuing nature-based solutions for urban water management from multiple perspectives - ScienceDirect (tcd.ie)",
        "doi": "https://doi.org/10.1016/j.envres.2017.05.043",
        "title": "Comprehending the multiple 'values' of green infrastructure - Valuing nature-based solutions for urban water management from multiple perspectives",
        "year": "2017",
        "country": "UK",
        "place_name": "Sheffield",
        "latitude": "53.3836",
        "longitude": "-1.4669",
        "indicator": "Water",
        "sub_indicator": "Flooding",
        "study_type": "Modelling",
        "study_duration": "Years",
        "nbs_type": "Green Space",
        "nbs_setting": "Urban",
        "nbs_scale": "Many",
        "nbs_effect": "Enhanced habitat, better recreational value, improved flood risk management"
    },
    {
        "id_number": "41",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "Green Roof",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "42",
        "link": "Nature based measures increase freshwater biodiversity in agricultural catchments - ScienceDirect (tcd.ie)",
        "doi": "https://doi.org/10.1016/j.biocon.2020.108515",
        "title": "Nature based measures increase freshwater biodiversity in agricultural catchments",
        "year": "2020",
        "country": "UK",
        "place_name": "Skeffington",
        "latitude": "52.6166",
        "longitude": "-0.9082",
        "indicator": "Other",
        "sub_indicator": "Ecology",
        "study_type": "Measurement",
        "study_duration": "Years",
        "nbs_type": "Water Structure",
        "nbs_setting": "Rural",
        "nbs_scale": "Many",
        "nbs_effect": "To intercept pollutants, store water and promote biodiversity"
    },
    {
        "id_number": "43",
        "link": "Understanding the relationship between urban blue infrastructure and land surface temperature - ScienceDirect (tcd.ie)",
        "doi": "https://doi.org/10.1016/j.scitotenv.2019.133742",
        "title": "Understanding the relationship between urban blue infrastructure and land surface temperature",
        "year": "2019",
        "country": "China",
        "place_name": "Wuhan",
        "latitude": "30.5833",
        "longitude": "114.2833",
        "indicator": "Heat",
        "sub_indicator": "Thermal Comfort",
        "study_type": "Measurement",
        "study_duration": "Months",
        "nbs_type": "Water Structure",
        "nbs_setting": "Urban",
        "nbs_scale": "Many",
        "nbs_effect": "Improve urban thermal environment"
    },
    {
        "id_number": "44",
        "link": "https://journal.hep.com.cn/laf/EN/article/downloadArticleFile.do?attachType=PDF&id=27948",
        "doi": "http://dx.doi.org/10.15302/J-LAF-1-020028",
        "title": "Mitigation of Urban Heat Island Effect with Small-Scale Parks - An Empirical Study on Community Parks in Nanjing, Jiangsiu Province",
        "year": "2020",
        "country": "China",
        "place_name": "Yancheng",
        "latitude": "33.3833",
        "longitude": "120.1167",
        "indicator": "Heat",
        "sub_indicator": "Thermal Comfort",
        "study_type": "Modelling",
        "study_duration": "N/A",
        "nbs_type": "Green Space",
        "nbs_setting": "Urban",
        "nbs_scale": "Many",
        "nbs_effect": "Improve urban thermal environment"
    },
    {
        "id_number": "45",
        "link": "https://onlinelibrary.wiley.com/doi/10.1002/ldr.3305",
        "doi": "https://doi.org/10.1002/ldr.3305",
        "title": "The potential of straw mulch as a nature-based solution for soil erosion in olive plantation treated with glyphosate: A biophysical and socioeconomic assessment",
        "year": "2020",
        "country": "Spain",
        "place_name": "Llanera de Ranes",
        "latitude": "38.9944",
        "longitude": "-0.5753",
        "indicator": "Other",
        "sub_indicator": "Erosion",
        "study_type": "Measurement",
        "study_duration": "Years",
        "nbs_type": "Other",
        "nbs_setting": "Rural",
        "nbs_scale": "Single",
        "nbs_effect": "Soil erosion can be controlled by using Straw mulch "
    },
    {
        "id_number": "46",
        "link": "https://www.mdpi.com/2071-1050/12/2/565",
        "doi": "https://doi.org/10.3390/su12020565",
        "title": "Nature-Based Solution for Reducing CO2 Levels in Museum Environments: A Phytoremediation Study for the Leonardo da Vinci's \"Last Supper\"",
        "year": "2020",
        "country": "Italy",
        "place_name": "Santa Maria delle Grazie",
        "latitude": "45.4658",
        "longitude": "9.1711",
        "indicator": "Air",
        "sub_indicator": "Carbon Oxides",
        "study_type": "Measurement",
        "study_duration": "Years",
        "nbs_type": "Green Space",
        "nbs_setting": "Urban",
        "nbs_scale": "Single",
        "nbs_effect": "Increasing the sustainability of air-tight museum environments"
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": "",
        "link": "",
        "doi": "",
        "title": "",
        "year": "",
        "country": "",
        "place_name": "",
        "latitude": "",
        "longitude": "",
        "indicator": "",
        "sub_indicator": "",
        "study_type": "",
        "study_duration": "",
        "nbs_type": "",
        "nbs_setting": "",
        "nbs_scale": "",
        "nbs_effect": ""
    },
    {
        "id_number": ""
    }
]